### ISSUE TITLE
Find a way to connect COM port to javscript GUI

### ISSUE THREAD

**Issue by FL0WL0W** [FL0WL0W/EFIGenie#2]
potential options
uart web proxy
electron
browser extensions

**Comment by FL0WL0W** [comment]
@kolojoe take this python script and turn it into an HTTP call

https://github.com/FL0WL0W/EFIGenieSTM32F401C/blob/master/Serial.py

**Comment by karniv00l** [comment]
You may also consider WebSockets it should be more performant. I think that having a dedicated backend for serial communication or OS-specific stuff is a good call, that way you can run it either in a browser, electron, Tauri, or any other wrapper.

**Comment by FL0WL0W** [comment]
@karniv00l I agree about websockets to make it more performant. the python solution is a temporary solution just to get going. It logged about 5ms round trip for the http post request, through usb and back. will revisit this later for the additional solutions like we talked about (ESP8266/32, Electron, etc.)
