### ISSUE TITLE
QS: 2Stroke Support?

### ISSUE THREAD

**Issue by Platin21** [FL0WL0W/EFIGenie#37]
I'm just asking if there is or if it would be possible to make this run with a 2t engine. (Talking Especially about those on a motorcycle). I guess there one would have to add the barometric sensor and injection of oil if not already required to premix.

I guess a T4 motorcycle would work as one cylinder config?

**Comment by FL0WL0W** [comment]
Yes, you can just configure a 2 stroke engine as a 2 cylinder, using the same coil and injector output.
